CREATE TABLE IF NOT EXISTS OMONEY_LOG (
             ID  INTEGER NOT NULL AUTO_INCREMENT,          
	     ORDER_ID  VARCHAR (25) NOT NULL UNIQUE,
             CURRENCY VARCHAR (10) NOT NULL,
             AMOUNT float(10,3) NOT NULL,
             LOGGED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
             LANG VARCHAR (10) NOT NULL,
             REFERENCE VARCHAR (50) NOT NULL,
             STATUS VARCHAR (10) DEFAULT 'PENDING',
             PAY_TOKEN VARCHAR (75),
             NOTIFY_TOKEN VARCHAR (75) UNIQUE,
             TXNID VARCHAR (50),
             PRIMARY KEY (ID , ORDER_ID)
);

CREATE TABLE IF NOT EXISTS OMONEY_KEYS (
	     ID  INTEGER NOT NULL AUTO_INCREMENT,   
             access_token  VARCHAR (50) NOT NULL UNIQUE,
             LOGGED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
             PRIMARY KEY (ID)
);
